language: nix

before_deploy:
  - mkdir pages
  - cp -rf result/* pages/

deploy:
  local-dir: pages
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
